# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Track the .NET SDK version via global.json
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly

  # Track NuGet package dependencies
  - package-ecosystem: nuget
    directories:
      - /src/Womb
      - /src/ThirdParty/SDL2
      - /examples/Playground
    schedule:
      interval: weekly
