name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        configuration:
          - Debug
          - Release
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Build Womb library [${{ matrix.configuration }}]
      run: |
        dotnet build --no-restore --configuration ${{ matrix.configuration }} src/Womb

    - name: Build examples/Playground [${{ matrix.configuration }}]
      run: |
        dotnet build --no-restore --configuration ${{ matrix.configuration }} examples/Playground

    - name: Test [${{ matrix.configuration }}]
      if: ${{ matrix.configuration }} == 'Debug'
      run: |
        dotnet test --no-build
